/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with
 and
, the first
 terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

const DEFAULT_END: usize = 4000000;

pub fn solve(end: Option<usize>) {
    let end = if let Some(end) = end {
        end
    } else {
        DEFAULT_END
    };

    let mut total: usize = 0;
    let mut a = 0;
    let mut b = 1;
    loop {
        let temp_b = a + b;
        a = b;
        b = temp_b;
        if b >= end {
            break;
        }
        if b % 2 == 0 {
            total += b
        }
    }
    println!("Even Fibonacci Numbers up to {end} is {total}.");
}
